version: "3"

services:
  loader_data:
    build:
      context: ..
      dockerfile: loader_data/Dockerfile
    restart: "no"
    command: bash -c "./process_fire/loader_data/startup.sh"
    volumes:
      - ./data/:/home/py-user/process_fire/loader_data/data
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      .env
    environment:
      db_name: "${db_name}"
      db_user: "${db_user}"
      db_password: "${db_password}"
      db_port: "${db_port}"
      db_host: "postgres" #"${db_host}"

  postgres:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      .env
    environment:
#      PGDATA: /var/lib/postgresql/data/
      POSTGRES_PASSWORD: "${db_password}"
      POSTGRES_DB: "${db_name}"
      POSTGRES_USER: "${db_user}"

volumes:
  postgres_db_volume:
